<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Add Applicant</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <?php
    if ($error) {
        echo "<div class='error-text invalid-login'>$error</div>";
    }
    ?>
    <form method="post" action="/admin/applicants/add" class="container">
        <h1>Add an Applicant</h1>
        <h2>Applicant</h2>
        <div class="form-group">
            <div class="form-group">
                <label for="name">Name <span class="form-asterisk">*</span></label>
                <input class="input-width-full" type="text" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="email">E-mail <span class="form-asterisk">*</span></label>
                <input class="input-width-full" type="email" id="email" name="email" required>
            </div>
            <div class="btn-width bottom-margin-75">
                <input class="btn" type="submit" value="Submit Applicant">
            </div>
            <h2>Application</h2>
            <div class="form-group">
                <label for="why">Why do you want to become a developer?</label>
                <textarea id="why" name="why"></textarea>
            </div>
            <div class="form-group">
                <label for="experience">Any past coding experience?</label>
                <textarea id="experience" name="experience"></textarea>
            </div>
            <div class="form-group flex">
                <input id="diversitech" name="diversitech" type="checkbox" value='1'>
                <label for="diversitech">Apply for Diversitech funding</label>
            </div>
            <div class="form-group">
                <label for="circumstance_id">What best describes your circumstances?</label>
                <select name="circumstance_id" id="circumstance_id">
                    <option value="0">Select option</option>
                    <?php foreach ($circumstances as $circumstanceOption): ?>
                        <option value="<?= $circumstanceOption['id']; ?>"><?= $circumstanceOption['option']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="funding_id">How would you like to fund your place?</label>
                <select name="funding_id" id="funding_id">
                    <option value="0">Select option</option>
                    <?php foreach ($funding as $fundingOption): ?>
                        <option value="<?= $fundingOption['id']; ?>"><?= $fundingOption['option']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="cohort_id">When would you like to start your course?</label>
                <select name="cohort_id" id="cohort_id">
                    <option value="0">Select option</option>
                    <?php foreach ($cohorts as $cohort): ?>
                        <option value="<?= $cohort->getId(); ?>"><?= $cohort->getDate(); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="dob">Date of Birth</label>
                <input type="date" id="dob" name="dob">
            </div>
            <div class="form-group">
                <label for="phone">Phone number</label>
                <input type="tel" id="phone" name="phone">
            </div>
            <div class="form-group">
                <label for="address">Address</label>
                <textarea id="address" name="address"></textarea>
            </div>
            <div class="form-group">
                <label for="heard_about_id">How did you hear about us?</label>
                <select name="heard_about_id" id="heard_about_id">
                    <option value="0">Select option</option>
                    <?php foreach ($hearAboutUs as $hearAboutUsOption): ?>
                        <option value="<?= $hearAboutUsOption['id']; ?>"><?= $hearAboutUsOption['option']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group flex">
                <input id="age_confirmation" name="age_confirmation" type="checkbox" value='1'>
                <label for="age_confirmation">I will be at least 18 years of age before my chosen course start date</label>
            </div>
            <div class="form-group flex">
                <input id="newsletter" name="newsletter" type="checkbox" value='1'>
                <Label for="newsletter">I would like to receive email updates from iO Academy</Label>
            </div>
            <div class="form-group flex">
                <input id="eligible" name="eligible" type="checkbox" value='1'>
                <Label for="eligible">I am eligible to live and work in the UK</Label>
            </div>
            <div class="form-group flex">
                <input id="terms" name="terms" type="checkbox" value='1'>
                <Label for="terms">I accept the terms and conditions</Label>
            </div>
            <div class="btn-width">
                <input class="btn" type="submit" value="Submit Applicant & Application">
            </div>
        </div>
    </form>
</main>
</body>
</html>
