<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Add Applicant</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <form method="post" action="/admin/applicant/add" class="container">
        <h1>Add Applicant</h1>
        <h2>Applicant</h2>
        <div class="form-group">
            <div class="form-group">
                <label for="name">Name <span class="form-asterisk">*</span></label>
                <input class="input-width-full" type="text" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="email">E-mail <span class="form-asterisk">*</span></label>
                <input class="input-width-full" type="email" id="email" name="email" required>
            </div>
            <div class="btn-width bottom-margin-75">
                <input class="btn" type="submit" value="Submit Applicant">
            </div>
            <h2>Application</h2>
            <div class="form-group">
                <label for="why">Why would you like to become a developer?</label>
                <textarea id="why" name="why"></textarea>
            </div>
            <div class="form-group">
                <label for="experience">Experience</label>
                <textarea id="experience" name="experience"></textarea>
            </div>
            <div class="form-group flex">
                <input id="diversitech" name="diversitech" type="checkbox" value='1'>
                <label for="diversitech">I confirm I am Diversitech qualified.</label>
            </div>
            <div class="form-group">
                <label for="circumstance_id">circumstance</label>
                <select name="circumstance_id" id="circumstance_id">
                    <?php foreach ($circumstanceOptions as $circumstanceOption): ?>
                        <option value="<?= $circumstanceOption['id']; ?>"><?= $circumstanceOption['option']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="funding_id">Funding</label>
                <select name="funding_id" id="funding_id">
                    <?php foreach ($fundingOptions as $fundingOption): ?>
                        <option value="<?= $fundingOption['id']; ?>"><?= $fundingOption['option']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="cohort_id">Cohort start date</label>
                <select name="cohort_id" id="cohort_id">
                    <?php foreach ($cohorts as $cohort): ?>
                        <option value="<?= $cohort['id']; ?>"><?= $cohort['date']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="dob">Date of Birth</label>
                <input type="date" id="dob" name="dob">
            </div>
            <div class="form-group">
                <label for="phone">Telephone number</label>
                <input type="tel" id="phone" name="phone">
            </div>
            <div class="form-group">
                <label for="address">Address:</label>
                <textarea id="address" name="address"></textarea>
            </div>
            <div class="form-group">
                <label for="heard_about_id">Hear about us</label>
                <select name="heard_about_id" id="heard_about_id">
                    <?php foreach ($hearAboutUsOptions as $hearAboutUsOption): ?>
                        <option value="<?= $hearAboutUsOption['id']; ?>"><?= $hearAboutUsOption['option']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group flex">
                <input id="age_confirmation" name="age_confirmation" type="checkbox" value='1'>
                <label for="age_confirmation">I confirm I will be at least 18 years before my chosen cohort.</label>
            </div>
            <div class="form-group flex">
                <input id="newsletter" name="newsletter" type="checkbox" value='1'>
                <Label for="newsletter">I confirm I would like to subscribe to the newsletter.</Label>
            </div>
            <div class="form-group flex">
                <input id="eligible" name="eligible" type="checkbox" value='1'>
                <Label for="eligible">I confirm I am eligible to study in the UK.</Label>
            </div>
            <div class="form-group flex">
                <input id="terms width-20" name="terms" type="checkbox" value='1'>
                <Label for="terms">T&C's read and agreed.</Label>
            </div>
            <div class="btn-width">
                <input class="btn" type="submit" value="Submit Applicant & Application">
            </div>
        </div>
    </form>
</main>
</body>
</html>
