<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Academy Portal</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main class="admin">
    <div class="container">
        <div class="links">
            <a href="/admin/applicants">Applicants</a>
            <a href="/admin/courses">Courses</a>
            <a href="/admin/cohorts">Cohorts</a>
        </div>
    </div>
</main>
</body>
</html>