<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Applicants</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <div class="container">
        <h1>Applicants</h1>
        <?php if (count($applicants) === 0): ?>
            No applicants found
        <?php else: ?>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Application Date</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($applicants as $applicant): ?>
                <tr>
                    <td><?php echo $applicant->getName(); ?></td>
                    <td><?php echo $applicant->getEmail(); ?></td>
                    <td><?php echo $applicant->getApplicationDate(); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php endif; ?>

        <div class="pagination">
            <a href="?page=<?= $previousPage; ?>" class="prev <?php if ($previousPage === 0) echo 'disabled' ?>">Previous</a>
            <?php
            for ($i = 1; $i <= $pageCount; $i++) {
                if ($i == $currentPage) {
                    echo "<a href='?page=$i' class='active'>$i</a>";
                } else {
                    echo "<a href='?page=$i'>$i</a>";
                }
            }
            ?>
            <a href="?page=<?= $nextPage; ?>" class="next <?php if ($nextPage > $pageCount) echo 'disabled' ?>">Next</a>
        </div>

    </div>
</main>
</body>
</html>