<?php
/**
 * @var $cohorts \Portal\Entities\Cohort[]

 */
?>
<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Cohorts</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <div class="container">
        <h1>Cohorts</h1>
        <?php if (count($cohorts) === 0): ?>
            No cohorts
        <?php else: ?>
            <table>
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Course</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($cohorts as $cohort): ?>
                    <tr>
                        <td><?= $cohort->getDate(); ?></td>
                        <td><?= $cohort->getCourse()->getShortName(); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>
</main>
</body>
</html>