<?php
/**
 * @var $courses \Portal\Entities\Course[]

 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Courses</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <div class="container">
        <div class="titleLink">
            <h1>Courses</h1>
            <a class="btn" href="/admin/courses/add">Add Course</a>
        </div>
        <?php if (count($courses) === 0): ?>
            No courses
        <?php else: ?>
            <table>
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Abbreviation</th>
                    <th>Remote</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($courses as $course): ?>
                    <tr>
                        <td><?= $course->getName(); ?></td>
                        <td><?= $course->getShortName(); ?></td>
                        <td><?= $course->getRemote() ? '<i class="fa-solid fa-check"></i>' : '<i class="fa-solid fa-xmark"></i>'  ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>
</main>
</body>
</html>