<?php
/**
 * @var $applicant \Portal\Entities\Applicant
 * @var $previousPage int
 * @var $nextPage int
 * @var $pageCount int
 * @var $currentPage int
 */

$application = $applicant->getApplication();
?>
<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Applicant - <?= $applicant->getName(); ?></title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <div class="container">

        <form>
            <h2>Personal Information</h2>
            <label for="name">name</label>
            <input id="name" value="<?= $applicant->getName() ?>">
            <label for="email">Email</label>
            <input id="email" value="<?= $applicant->getEmail() ?>">
            <label for="phone">Phone</label>
            <input id="phone" value="  <?php if ($application): ?>
                    <?= $application->getPhone() ?>
                <?php else: ?>No phone number
                <?php endif; ?>">
            <section class="details">
                <div>
                    <h2>Application Info</h2>

                    <label for="cohort">Cohort</label>
                    <input id="cohort" value="<?= $application->getCohort()?>">

                    <label for="background">Background Info</label>
                    <select name="background" id="background">
                        <option disabled <?php
                        if ($application->getCircumstance() == 0 | null) echo "selected" ?>>Not
                            selected
                        </option>
                        <option value="1" <?php if ($applicant->getCircumstanceId() == 1) echo "selected" ?>>Changing
                            careers
                        </option>
                        <option value="2" <?php if ($applicant->getCircumstanceId() == 2) echo "selected" ?>>Returning
                            to work
                        </option>
                        <option value="3" <?php if ($applicant->getCircumstanceId() == 3) echo "selected" ?>>Recent
                            university graduate
                        </option>
                        <option value="4" <?php if ($applicant->getCircumstanceId() == 4) echo "selected" ?>>School
                            leaver
                        </option>
                    </select>

                    <label for="why">Application Reason</label>
                    <input id="why" value="<?= $application->getWhy() ?>">

                    <label for="experience">Code experience</label>
                    <input id="experience" value="<?= $application->getExperience() ?>">

                    <label for="hearAbout">Heard about us</label
                    <input id="hearAbout" value="<?= $application->getHearAbout() ?>">

                </div>
                <div>
                    <label>Diversitech</label>
                    <br>
                    <input name="diversitech" id="yes" type="radio"
                           value="" <?php if ($application->getDiversitech() == true) echo "checked" ?>>
                    <label for="yes">yes</label>
                    <input name="diversitech" id="no" type="radio"
                           value="" <?php if ($application->getDiversitech() == false) echo "checked" ?>>
                    <label for="no">no</label>
                </div>

                <div>
                    <label>Over 18</label>
                    <br>
                    <input name="ageConfirmation" id="yes" type="radio"
                           value="" <?php if ($application->getAgeConfirmation() == true) echo "checked" ?>>
                    <label for="yes">yes</label>
                    <input name="ageConfirmation" id="no" type="radio"
                           value="" <?php if ($application->getAgeConfirmation() == false) echo "checked" ?>>
                    <label for="no">no</label>
                </div>

                <div>
                    <label>Newsletter signup</label>
                    <br>
                    <input name="newsletter" id="yes" type="radio"
                           value="" <?php if ($application->getNewsletter() == true) echo "checked" ?>>
                    <label for="yes">yes</label>
                    <input name="newsletter" id="no" type="radio"
                           value="" <?php if ($application->getNewsletter() == false) echo "checked" ?>>
                    <label for="no">no</label>
                </div>

                <div>
                    <label>Eligible to study in the UK</label>
                    <br>
                    <input name="eligible" id="yes" type="radio"
                           value="" <?php if ($application->getEligible() == true) echo "checked" ?>>
                    <label for="yes">yes</label>
                    <input name="eligible" id="no" type="radio"
                           value="" <?php if ($application->getEligible() == false) echo "checked" ?>>
                    <label for="no">no</label>
                </div>

        </form>
    </div>
</main>
</body>
</html>