<?php
/**
 * @var $applicant \Portal\Entities\Applicant
 * @var $previousPage int
 * @var $nextPage int
 * @var $pageCount int
 * @var $currentPage int
 */

$application = $applicant->getApplication();
?>
<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Applicant - <?= $applicant->getName(); ?></title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <div class="container">

        <form>
            <h2>Personal Information</h2>
            <div class="form-group">
                <label for="name">name</label>
                <input id="name" value="<?= $applicant->getName() ?>">
                <label for="email">Email</label>
                <input id="email" value="<?= $applicant->getEmail() ?>">
                <label for="phone">Phone</label>
                <input id="phone"
                       value="<?php if ($application): ?><?= $application->getPhone() ?><?php else: ?>No phone number<?php endif; ?>">
                <section class="appInfo">
            </div>
            <h2>Application Info</h2>
            <div class="applicationInfo">
                <div class="form-group">

                    <label for="cohort_id">Cohort start date</label>
                    <select name="cohort_id" id="cohort_id">
                        <?php
                        foreach ($cohorts as $cohort) {
                            if ($cohort['date'] == $application->getCohort()) {
                                $selected = 'selected';
                                echo $selected;
                            } else {
                                $selected = "";
                            }
                            echo "<option value='{$cohort['id']}' {$selected}>{$cohort['date']}</option>";
                        };
                        ?>
                    </select>

                    <label for="why">Application Reason</label>
                    <input id="why" value="<?= $application->getWhy() ?>">

                    <label for="heard_about">Circumstance</label>
                    <select name="heard_about_id" id="heard_about">
                        <?php
                        foreach ($circumstances as $circumstance) {
                            if ($circumstance['option'] == $application->getCircumstance()) {
                                $selected = 'selected';
                                echo $selected;
                            } else {
                                $selected = "";
                            }
                            echo "<option value='{$circumstance['id']}' {$selected}>{$circumstance['option']}</option>";
                        };
                        ?>
                    </select>

                    <label for="experience">Code experience</label>
                    <input id="experience" value="<?= $application->getExperience() ?>">



                    <label for="heard_about">Heard about us from</label>
                    <select name="heard_about_id" id="heard_about">
                        <?php
                        foreach ($hearAboutUs as $hear) {
                            if ($hear['option'] == $application->getHearAbout()) {
                                $selected = 'selected';
                                echo $selected;
                            } else {
                                $selected = "";
                            }
                            echo "<option value='{$hear['id']}' {$selected}>{$hear['option']}</option>";
                        };
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <Label for="diversitech">Diversitech Qualification</Label>
                <div class="width-20">
                    <input id="diversitech" name="diversitech" type="checkbox"
                           value='1' <?php if ($application->getDiversitech() == 1) echo "checked" ?>>
                </div>
            </div>
            <div class="form-group">
                <Label for="ageConfirmation">Over 18</Label>
                <div class="width-20">
                    <input id="ageConfirmation" name="ageConfirmation" type="checkbox"
                           value='1' <?php if ($application->getAgeConfirmation()) echo "checked" ?>>
                </div>
            </div>
            <div class="form-group">
                <Label for="newsletter">Newsletter signup</Label>
                <div class="width-20">
                    <input id="newsletter" name="newsletter" type="checkbox"
                           value='1' <?php if ($application->getNewsletter()) echo "checked" ?>>
                </div>
            </div>
            <div class="form-group">
                <Label for="eligible">Eligible to work in UK</Label>
                <div class="width-20">
                    <input id="eligible" name="eligible" type="checkbox"
                           value='1' <?php if ($application->getEligible()) echo "checked" ?>>
                </div>
            </div>
            <button formmethod="post" formaction="">Submit</button>
        </form>
    </div>
</main>
</body>
</html>