<?php
/**
 * @var $email_error ?string
 * @var $error ?string
 */
?>
<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Login</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<main class="login">
    <section>
        <h1>Login</h1>
        <form method="post" action="/login">
            <div class="form-group">
                <label for="email">Email (Required)</label>
                <input type="email" name="email" id="email" required>
                <?php
                if ($email_error) {
                    echo "<div class='error-text'>$email_error</div>";
                }
                ?>
            </div>
            <div class="form-group">
                <label for="password">Password (Required)</label>
                <input type="password" name="password" id="password" required>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" id="submit" class="btn btn-success">
            </div>
            <?php
            if ($error) {
                echo "<div class='error-text invalid-login'>$error</div>";
            }
            ?>
        </form>
    </section>
</main>
</body>
</html>