<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Login</title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<main class="login">
    <h1>Login</h1>
    <div class="container">
        <form method="post" action="/login">
            <div class="form-group">
                <label for="userEmail">Email (Required)</label>
                <input type="email" name="userEmail" id="userEmail" required class="form-control">
                <span id="userEmailWarning"></span>
            </div>
            <div class="form-group">
                <label for="password">Password (Required)</label>
                <input type="password" name="password" id="password" required class="form-control">
                <span id="passwordWarning"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" id="submit" class="btn btn-success">
                <span id="submitWarning" class="req"></span>
            </div>
            <div id="error-message">
                <?php
                    if (isset($_GET['error'])) {
                        echo $_GET['error'];
                    }
                ?>
            </div>
        </form>
    </div>

</main>
</body>
</html>