<?php
/**
 * @var $applicant \Portal\Entities\ApplicantEntity
 */
?>
<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Applicant - <?= $applicant->getName(); ?></title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main class="single-applicant">
    <div class="container">
        <div class="applicant-header">
            <h1>Applicant Details</h1>
            <p><?= $applicant->getFormattedApplicationDate() ?></p>
        </div>

        <section class="details">
            <h2>Personal Information</h2>
            <p><span>Name:</span> <?= $applicant->getName() ?></p>
            <p><span>Email:</span> <?= $applicant->getEmail() ?></p>
            <p><span>Phone:</span> <?= $applicant->getApplication()->getPhone() ?></p>
        </section>

        <section class="details">
            <h2>Application Info</h2>
            <p><span>Cohort:</span> <?= $applicant->getApplication()->getCohort() ?></p>
            <p><span>Background info:</span> <?= $applicant->getApplication()->getCircumstance() ?></p>
            <p><span>Application reason:</span><br /> <?= $applicant->getApplication()->getWhy() ?></p>
            <p><span>Code experience:</span><br /> <?= $applicant->getApplication()->getExperience() ?></p>
            <p><span>Heard about us:</span> <?= $applicant->getApplication()->getHearAbout() ?></p>
            <p><span>Over 18:</span> <?= $applicant->getApplication()->getAgeConfirmation() ? 'Yes' : 'No' ?></p>
            <p><span>Newsletter signup:</span> <?= $applicant->getApplication()->getNewsletter() ? 'Yes' : 'No' ?></p>
            <p><span>Eligible to study in the UK:</span> <?= $applicant->getApplication()->getEligible() ? 'Yes' : 'No' ?></p>
            <p><span>Agreed to terms:</span> <?= $applicant->getApplication()->getTerms() ? 'Yes' : 'No' ?></p>
        </section>

    </div>
</main>
</body>
</html>