<?php
/**
 * @var $applicant \Portal\Entities\ApplicantEntity
 */

$application = $applicant->getApplication();
?>
<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Applicant - <?= $applicant->getName(); ?></title>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>
<main class="single-applicant">
    <div class="container">
        <div class="applicant-header">
            <h1>Applicant Details</h1>
            <p><?= $applicant->getFormattedApplicationDate() ?></p>
        </div>

        <section class="details">
            <h2>Personal Information</h2>
            <p><span>Name:</span> <?= $applicant->getName() ?></p>
            <p><span>Email:</span> <?= $applicant->getEmail() ?></p>
            <p><span>Phone:</span> <?= $application->getPhone() ?></p>
        </section>

        <section class="details">
            <h2>Application Info</h2>
            <p><span>Cohort:</span> <?= $application->getCohort() ?></p>
            <p><span>Background info:</span> <?= $application->getCircumstance() ?></p>
            <p><span>Application reason:</span><br /> <?= $application->getWhy() ?></p>
            <p><span>Code experience:</span><br /> <?= $application->getExperience() ?></p>
            <p><span>Heard about us:</span> <?= $application->getHearAbout() ?></p>
            <p><span>Diversitech:</span> <?= $application->getDiversitech() ? 'Yes' : 'No' ?></p>
            <p><span>Over 18:</span> <?= $application->getAgeConfirmation() ? 'Yes' : 'No' ?></p>
            <p><span>Newsletter signup:</span> <?= $application->getNewsletter() ? 'Yes' : 'No' ?></p>
            <p><span>Eligible to study in the UK:</span> <?= $application->getEligible() ? 'Yes' : 'No' ?></p>
            <p><span>Agreed to terms:</span> <?= $application->getTerms() ? 'Yes' : 'No' ?></p>
        </section>
    </div>
</main>
</body>
</html>