<header class="container">
    <div class="icons">
        <a href="https://io-academy.uk/" target="_blank">
            <i class="fa-solid fa-globe"></i>
            <div>Website</div>
        </a>
        <a href="https://aptitude-test.io-academy.uk/" target="_blank">
            <i class="fa-solid fa-list"></i>
            <div>Apt Test</div>
        </a>
        <a href="https://drive.google.com/drive/folders/0AFB6MvsmFGWZUk9PVA" target="_blank">
            <i class="fa-solid fa-folder"></i>
            <div>G Drive</div>
        </a>
    </div>

    <div class="logo"><img src="https://dev.io-academy.uk/logo.svg" alt="iO Academy"></div>
</header>