<div class="container">
    <header class="row">
        <div class="col row align-items-center justify-content-between">
            <a class="col text-center" href="https://io-academy.uk/" target="_blank">
                <i class="bi bi-globe"></i>
                <div>Website</div>
            </a>
            <a class="col text-center" href="https://aptitude-test.io-academy.uk/" target="_blank">
                <i class="bi bi-card-list"></i>
                <div>Apt Test</div>
            </a>
            <a class="col text-center" href="https://drive.google.com/drive/folders/0AFB6MvsmFGWZUk9PVA" target="_blank">
                <i class="bi bi-folder2-open"></i>
                <div>G Drive</div>
            </a>
        </div>

        <div class="col w-25"><img src="https://dev.io-academy.uk/logo.svg" alt="iO Academy"></div>
    </header>